- name: Ubuntu config
  hosts: ubuntu
  tasks:
    - name: create the .ssh directory if it is not there
      file:
        path: "/home/{{ anisble_user }}/.ssh"
        state: directory
        node: 0700
    - name: create authorized_keys file
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        state: touch
        node: 0644
    - name: copy over key block and append to authorized_keys
      blockinfile:
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        block: "{{ public_key }}"

    - name: create sudoers dropin file for 480
      file:
        path: /etc/sudoers.d/480
        state: touch
        node: 0440
      become: yes
    
    - name: create a drop in entry in /etc/sudoers.d/480
      blockinfile:
        dest: "/etc/sudoers.d/480"
        block: "{{ anisble_user }} ALL=(ALL) NOPASSWD: ALL"
      become: yes

    - name: set the hostname
      hostname:
        name: "{{ hostname }}"
      become: yes

    - name: add host to hosts file
      lineinfile:
        path: /etc/hosts
        line: '127.0.0.1 {{ hostname }}'
      become: yes

    - name: Netplan Apply
      become: yes
      template:
        src: files/ubuntu/netplan-config.yaml.j2
        dest: /etc/netplan/00-installer-config.yaml
        mode: "0644"
        owner: root
        group: root

    - name: bounce the box
      shell: "sleep 5 && shutdown -r"
      become: yes
      async: 1
      poll: 0