# Usage: ansible-playbook -i inventories/linux.yaml --ask-pass wazuh-server.yaml
- name: Wazuh Server Config
  hosts: wazuh_server
  tasks:
    - name: Install Wazuh Server Script
      ansible.builtin.shell:
        chdir: /home/{{ ansible_user }}/
        cmd: curl -sO https://packages.wazuh.com/4.3/wazuh-install.sh
    
    - name: Run Wazuh Server Script
      ansible.builtin.shell:
        cmd: bash ./wazuh-install.sh -a -i
        chdir: /home/{{ ansible_user }}/
      become: true
    
    # - name: bounce the box
    #   shell: "sleep 5 && shutdown -r"
    #   become: yes
    #   async: 1
    #   poll: 0