linux:
  hosts:
    children:
      rocky:
        hosts:
          10.0.5.77:
            hostname: rocky-1
            lan_ip: 10.0.5.10
          10.0.5.75:
            hostname: rocky-2
            lan_ip: 10.0.5.11
          10.0.5.76:
            hostname: rocky-3
            lan_ip: 10.0.5.12
        vars:
          device: "{{ ansible_default_ipv4.interface }}"

      ubuntu:
        hosts:
          10.0.5.78:
            hostname: ubuntu-1
            lan_ip: 10.0.5.30
          10.0.5.79:
            hostname: ubuntu-2
            lan_ip: 10.0.5.31

  vars:
    public_key: ""
    anisble_user: champuser
    prefix: 24
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue1.local