windows:
  hosts:
  children:
    dc:
      hosts:
        10.0.5.5:
          hostname: dc-blue1
    file_server:
      hosts:
        10.0.5.6:
          hostname: fs-blue1
  
  vars:
    ansible_user: deployer
    ansible_shell_type: powershell
    csv_path: files\windows\userandgroupwithpasswords.csv
    group_path: files\windows\groups.csv